version: '3'

services:
  webapireidoalmoco:
    image: webapireidoalmoco:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webapireidoalmoco$
    volumes:
      - C:\Users\eduar\source\repos\WebMvcReiDoAlmoco\WebApiReiDoAlmoco:C:\app
      - C:\Users\eduar\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_webapireidoalmoco$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webapireidoalmoco$ bin\\Debug\\netcoreapp2.0\\WebApiReiDoAlmoco.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"

  webmvcdoalmoco:
    image: webmvcdoalmoco:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webmvcdoalmoco$
    volumes:
      - C:\Users\eduar\source\repos\WebMvcReiDoAlmoco\WebMvcDoAlmoco:C:\app
      - C:\Users\eduar\onecoremsvsmon:C:\remote_debugger:ro
#$nuget_volume_mapping_webmvcdoalmoco$
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webmvcdoalmoco$ bin\\Debug\\netcoreapp2.0\\WebMvcDoAlmoco.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"

